### PR TITLE
Feature/pagination

### PR DESCRIPTION
**Pull request by Levino**

### CODE REVIEW

**Comment by fanatid** [comment]
Yet one pagination implementation, based on promises: https://github.com/fanatid/blockchainjs/blob/459b53d7de96f97c59f0f0bd93c490dc545d8d40/lib/network/chain.js#L475
I don't see the way getting header `next-range` in browsers... I hope I'm wrong.

**Comment by Levino** [comment]
@fanatid Thanks for the example. What shall I do with it? Shall I change my code? Do you think your solution is better?

**Comment by fanatid** [comment]
It's just an example. My code not better for chain-node, because it's part of solid class that also have subscribe support through websocket. 
The more I wanted to know is there any way get all transaction hashes for address in browser?

**Comment by ryandotsmith** [comment]
Thanks for the suggestions on this feature. As a matter of fact, we are working on building a fresh Node.js library for Chain's API. We have addressed pagination in the new library. So... I'm going to close this PR for now. Thanks again for all of your feedback and suggestions!!

**Comment by Levino** [comment]
@ryandotsmith I still see commit like #24 When are you going to release the new version?

**Pull request closed without merging**
